name: Python Flask CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel  # Instala o wheel explicitamente
          pip install -r requirements.txt
      
      - name: Build Distribution
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Run Tests
        run: |
          pytest test_app.py
