name: Python Flask CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Utiliza a versão mais recente do checkout
        
      - name: Set up Python
        uses: actions/setup-python@v4  # Utiliza a versão mais recente do setup-python
        with:
          python-version: '3.8'
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Tests
        run: |
          pytest test_app.py

      - name: Build Application
        run: |
          python setup.py sdist bdist_wheel
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3  # Atualiza para a versão mais recente
        with:
          name: dist
          path: dist/*
